### PR TITLE
fix: stop spamming the google api

### PR DESCRIPTION
**Pull request by lewisfm**
Gets rid of the spam to the google api (several requests per second) while still updating info once per hour

### CODE REVIEW

**Comment by Craftzman7** [comment]
What's the reasoning behind this?

**Comment by lewisfm** [comment]
It uses unneccesary data, especially for people on mobile networks. There's not really a valid reason to have an infinite fetch loop.

**Comment by Craftzman7** [comment]
That's why there's a filter date. This transfers very little data. After leaving it open for ~30 seconds I hit 1MB of data transferred. 

Edit: This is meant to run on a singular RPI. That's all this is designed for.

**Comment by lewisfm** [comment]
You sent the link on the Discord so it seems like you expect multiple people to use it.

**Comment by Craftzman7** [comment]
If you could update it to fetch every 10 or 30 seconds I'll merge it.

> You sent the link on the Discord so it seems like you expect multiple people to use it.

That was really meant as a showcase. This isn't meant for use outside of the RPI.

**Comment by lewisfm** [comment]
I'll update it

**Review by Craftzman7 — CHANGES_REQUESTED** [review]
Update to a 10-30 second interval.

**Review by Craftzman7 — APPROVED** [review]

**Pull request merged**
